const cron = require('node-cron');
let ciudades = ["Guayaquil",
    "Quito",
    "Cuenca",
    "Santo Domingo",
    "Machala",
    "Duran",
    "Manta",
    "Portoviejo",
    "Loja",
    "Ambato",
    "Esmeraldas",
    "Quevedo",
    "Riobamba",
    "Gualaceo",
    "Lomas de Sargentillo",
    "Cariamanga",
    "Baños de Agua Santa",
    "Montalvo",
    "Macara",
    "San Miguel de Salcedo",
    "Zamora",
    "Puerto Ayora",
    "La Joya de los Sachas",
    "Salitre",
    "Tosagua",
    "Pelileo",
    "Pujili",
    "Tabacundo",
    "Puerto Lopez",
    "San Vicente",
    "Santa Ana",
    "Zaruma",
    "Balao",
    "Rocafuerte",
    "Yantzaza",
    "Cotacachi",
    "Santa Lucia",
    "Cumanda",
    "Palestina",
    "Alfredo Baquerizo Moreno",
    "Nobol",
    "Mocache",
    "Puebloviejo",
    "Portovelo",
    "Sucua",
    "Guano",
    "Pillaro",
    "Simon Bolivar",
    "Gualaquiza",
    "Paute",
    "Saquisili",
    "Cnel. Marcelino Maridueña",
    "Pajan",
    "San Miguel",
    "Puerto Baquerizo Moreno",
    "Catacocha",
    "Palenque",
    "Alausi",
    "Caluma",
    "Catarama",
    "Flavio Alfaro",
    "Colimes",
    "Echeandia",
    "Jama",
    "Isidro Ayora",
    "Muisne",
    "Santa Isabel",
    "Pedro Vicente Maldonado",
    "Biblian",
    "Archidona",
    "Junin",
    "Baba",
    "Pimampiro",
    "Camilo Ponce Enriquez",
    "San Miguel de Los Bancos",
    "El Tambo",
    "El Angel",
    "Alamor",
    "Chambo",
    "Chimbo",
    "Celica",
    "Chordeleg",
    "Balsas",
    "Saraguro",
    "El Chaco",
    "Giron",
    "Huaca",
    "Pichincha",
    "Chunchi",
    "Pallatanga",
    "Marcabeli",
    "Sigsig",
    "Urcuqui",
    "Loreto",
    "Rioverde",
    "Zumba",
    "Palora",
    "Mira",
    "El Pangui",
    "Puerto Quito",
    "Bolivar",
    "Sucre",
    "Chillanes",
    "Quero",
    "Guamote",
    "Cevallos",
    "Zapotillo",
    "Santiago de Mendez",
    "Zumbi",
    "Puerto El Carmen de Putumayo",
    "Patate",
    "Olmedo",
    "Puerto Villamil",
    "El Dorado de Cascales",
    "Lumbaqui",
    "Palanda",
    "Sigchos",
    "Pindal",
    "Guayzimi",
    "Baeza",
    "El Corazon",
    "Paccha",
    "Amaluza",
    "Las Naves",
    "San Fernando",
    "Gonzanama",
    "San Juan Bosco",
    "Yacuambi",
    "Santa Clara",
    "Arajuno",
    "Tarapoa",
    "Tisaleo",
    "Suscal",
    "Nabon",
    "Mocha",
    "La Victoria",
    "Guachapala",
    "Santiago",
    "Chaguarpamba",
    "Penipe",
    "Taisha",
    "Chilla",
    "Paquisha",
    "Carlos Julio Arosemena Tola",
    "Sozoranga",
    "Pucara",
    "Huamboya",
    "Quilanga",
    "Sevilla de Oro",
    "Mera",
    "Pablo Sexto",
    "Olmedo",
    "Deleg",
    "La Bonita",
    "El Pan",
    "Tiputini"
];
cron.schedule('*/59 * * * * ', () => {
    setTimeout(function() {
        for (let i in ciudades) {
            climaConsulta.getClima(ciudades2[i] + ", Ecuador")
                .then(respuesta => {
                    let resAPI_DB = respuesta;
                    let clima = new Clima({
                        ciudad: resAPI_DB.ciudad_bd,
                        pais: resAPI_DB.pais_bd,
                        latitud: resAPI_DB.latitud_bd,
                        longitud: resAPI_DB.longitud_bd,
                        hora_local: resAPI_DB.hora_local_bd,
                        temperatura: resAPI_DB.temperatura_bd,
                        descripcion_tiempo: resAPI_DB.descripcion_tiempo_bd,
                        velocidad_viento: resAPI_DB.velocidad_viento_bd,
                        grado_viento: resAPI_DB.grado_viento_bd,
                        direccion_viento: resAPI_DB.direccion_viento_bd,
                        presion: resAPI_DB.presion_bd,
                        precipitacion: resAPI_DB.precipitacion_bd,
                        humedad: resAPI_DB.humedad_bd,
                        capa_nubes: resAPI_DB.capa_nubes_bd,
                        sensacion_termica: resAPI_DB.sensacion_termica_bd,
                        visibilidad: resAPI_DB.visibilidad_bd
                    });
                    clima.save((err, climaDB) => {
                        if (err) throw err;
                    });
                })
                .catch(err => {
                    console.log(err);
                });
        }
    }, 60000);

});